title: "Manish Yadav"
author: "Manish Yadav"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}
  - {title: Resume, icon: mandalorian, url: "https://maneesh51.github.io/resume/", width="700" height="500"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:manish.yadav83@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/maneesh51"}
  - {title: Linkedin, icon: linkedin, url: "https://linkedin.com/in/manishyadav51"}
  - {title: Researchgate, icon: researchgate, url: "https://https://www.researchgate.net/profile/Manish-Yadav-16"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/manish_yadav4"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
